//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimelyDepotMVC.GGE4ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/", ConfigurationName="GGE4ServiceReference.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request) del mensaje SendAndCommitRequest no coincide con el valor predeterminado (http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/)
        [System.ServiceModel.OperationContractAttribute(Action="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/SendAndCommit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TimelyDepotMVC.GGE4ServiceReference.SendAndCommitResponse SendAndCommit(TimelyDepotMVC.GGE4ServiceReference.SendAndCommitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/SendAndCommit", ReplyAction="*")]
        System.Threading.Tasks.Task<TimelyDepotMVC.GGE4ServiceReference.SendAndCommitResponse> SendAndCommitAsync(TimelyDepotMVC.GGE4ServiceReference.SendAndCommitRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request) del mensaje SendAndCommitCheckRequest no coincide con el valor predeterminado (http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/)
        [System.ServiceModel.OperationContractAttribute(Action="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/SendAndCommitCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckResponse SendAndCommitCheck(TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/SendAndCommitCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckResponse> SendAndCommitCheckAsync(TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request) del mensaje TransactionInfoRequest no coincide con el valor predeterminado (http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/)
        [System.ServiceModel.OperationContractAttribute(Action="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/TransactionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TimelyDepotMVC.GGE4ServiceReference.TransactionInfoResponse TransactionInfo(TimelyDepotMVC.GGE4ServiceReference.TransactionInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/TransactionInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<TimelyDepotMVC.GGE4ServiceReference.TransactionInfoResponse> TransactionInfoAsync(TimelyDepotMVC.GGE4ServiceReference.TransactionInfoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request) del mensaje CheckTransactionInfoRequest no coincide con el valor predeterminado (http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/)
        [System.ServiceModel.OperationContractAttribute(Action="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/CheckTransactionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoResponse CheckTransactionInfo(TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/CheckTransactionInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoResponse> CheckTransactionInfoAsync(TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoRequest request);
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TransactionResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class Transaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exactIDField;
        
        private string passwordField;
        
        private string transaction_TypeField;
        
        private string dollarAmountField;
        
        private string surchargeAmountField;
        
        private string card_NumberField;
        
        private string transaction_TagField;
        
        private string track1Field;
        
        private string track2Field;
        
        private string pANField;
        
        private string authorization_NumField;
        
        private string expiry_DateField;
        
        private string cardHoldersNameField;
        
        private string verificationStr1Field;
        
        private string verificationStr2Field;
        
        private string cVD_Presence_IndField;
        
        private string zipCodeField;
        
        private string tax1AmountField;
        
        private string tax1NumberField;
        
        private string tax2AmountField;
        
        private string tax2NumberField;
        
        private string secure_AuthRequiredField;
        
        private string secure_AuthResultField;
        
        private string ecommerce_FlagField;
        
        private string xIDField;
        
        private string cAVVField;
        
        private string cAVV_AlgorithmField;
        
        private string reference_NoField;
        
        private string customer_RefField;
        
        private string reference_3Field;
        
        private string languageField;
        
        private string client_IPField;
        
        private string client_EmailField;
        
        private string user_NameField;
        
        private string currencyField;
        
        private bool partialRedemptionField;
        
        private bool partialRedemptionFieldSpecified;
        
        private Level3_Type level3Field;
        
        private string transarmorTokenField;
        
        private string cardTypeField;
        
        private string eANField;
        
        private bool virtualCardField;
        
        private bool virtualCardFieldSpecified;
        
        private string cardCostField;
        
        private string fraudSuspectedField;
        
        private PaypalTransactionDetails paypalResponseField;
        
        private SoftDescriptor_Type softDescriptorField;
        
        /// <comentarios/>
        public string ExactID {
            get {
                return this.exactIDField;
            }
            set {
                this.exactIDField = value;
                this.RaisePropertyChanged("ExactID");
            }
        }
        
        /// <comentarios/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <comentarios/>
        public string Transaction_Type {
            get {
                return this.transaction_TypeField;
            }
            set {
                this.transaction_TypeField = value;
                this.RaisePropertyChanged("Transaction_Type");
            }
        }
        
        /// <comentarios/>
        public string DollarAmount {
            get {
                return this.dollarAmountField;
            }
            set {
                this.dollarAmountField = value;
                this.RaisePropertyChanged("DollarAmount");
            }
        }
        
        /// <comentarios/>
        public string SurchargeAmount {
            get {
                return this.surchargeAmountField;
            }
            set {
                this.surchargeAmountField = value;
                this.RaisePropertyChanged("SurchargeAmount");
            }
        }
        
        /// <comentarios/>
        public string Card_Number {
            get {
                return this.card_NumberField;
            }
            set {
                this.card_NumberField = value;
                this.RaisePropertyChanged("Card_Number");
            }
        }
        
        /// <comentarios/>
        public string Transaction_Tag {
            get {
                return this.transaction_TagField;
            }
            set {
                this.transaction_TagField = value;
                this.RaisePropertyChanged("Transaction_Tag");
            }
        }
        
        /// <comentarios/>
        public string Track1 {
            get {
                return this.track1Field;
            }
            set {
                this.track1Field = value;
                this.RaisePropertyChanged("Track1");
            }
        }
        
        /// <comentarios/>
        public string Track2 {
            get {
                return this.track2Field;
            }
            set {
                this.track2Field = value;
                this.RaisePropertyChanged("Track2");
            }
        }
        
        /// <comentarios/>
        public string PAN {
            get {
                return this.pANField;
            }
            set {
                this.pANField = value;
                this.RaisePropertyChanged("PAN");
            }
        }
        
        /// <comentarios/>
        public string Authorization_Num {
            get {
                return this.authorization_NumField;
            }
            set {
                this.authorization_NumField = value;
                this.RaisePropertyChanged("Authorization_Num");
            }
        }
        
        /// <comentarios/>
        public string Expiry_Date {
            get {
                return this.expiry_DateField;
            }
            set {
                this.expiry_DateField = value;
                this.RaisePropertyChanged("Expiry_Date");
            }
        }
        
        /// <comentarios/>
        public string CardHoldersName {
            get {
                return this.cardHoldersNameField;
            }
            set {
                this.cardHoldersNameField = value;
                this.RaisePropertyChanged("CardHoldersName");
            }
        }
        
        /// <comentarios/>
        public string VerificationStr1 {
            get {
                return this.verificationStr1Field;
            }
            set {
                this.verificationStr1Field = value;
                this.RaisePropertyChanged("VerificationStr1");
            }
        }
        
        /// <comentarios/>
        public string VerificationStr2 {
            get {
                return this.verificationStr2Field;
            }
            set {
                this.verificationStr2Field = value;
                this.RaisePropertyChanged("VerificationStr2");
            }
        }
        
        /// <comentarios/>
        public string CVD_Presence_Ind {
            get {
                return this.cVD_Presence_IndField;
            }
            set {
                this.cVD_Presence_IndField = value;
                this.RaisePropertyChanged("CVD_Presence_Ind");
            }
        }
        
        /// <comentarios/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <comentarios/>
        public string Tax1Amount {
            get {
                return this.tax1AmountField;
            }
            set {
                this.tax1AmountField = value;
                this.RaisePropertyChanged("Tax1Amount");
            }
        }
        
        /// <comentarios/>
        public string Tax1Number {
            get {
                return this.tax1NumberField;
            }
            set {
                this.tax1NumberField = value;
                this.RaisePropertyChanged("Tax1Number");
            }
        }
        
        /// <comentarios/>
        public string Tax2Amount {
            get {
                return this.tax2AmountField;
            }
            set {
                this.tax2AmountField = value;
                this.RaisePropertyChanged("Tax2Amount");
            }
        }
        
        /// <comentarios/>
        public string Tax2Number {
            get {
                return this.tax2NumberField;
            }
            set {
                this.tax2NumberField = value;
                this.RaisePropertyChanged("Tax2Number");
            }
        }
        
        /// <comentarios/>
        public string Secure_AuthRequired {
            get {
                return this.secure_AuthRequiredField;
            }
            set {
                this.secure_AuthRequiredField = value;
                this.RaisePropertyChanged("Secure_AuthRequired");
            }
        }
        
        /// <comentarios/>
        public string Secure_AuthResult {
            get {
                return this.secure_AuthResultField;
            }
            set {
                this.secure_AuthResultField = value;
                this.RaisePropertyChanged("Secure_AuthResult");
            }
        }
        
        /// <comentarios/>
        public string Ecommerce_Flag {
            get {
                return this.ecommerce_FlagField;
            }
            set {
                this.ecommerce_FlagField = value;
                this.RaisePropertyChanged("Ecommerce_Flag");
            }
        }
        
        /// <comentarios/>
        public string XID {
            get {
                return this.xIDField;
            }
            set {
                this.xIDField = value;
                this.RaisePropertyChanged("XID");
            }
        }
        
        /// <comentarios/>
        public string CAVV {
            get {
                return this.cAVVField;
            }
            set {
                this.cAVVField = value;
                this.RaisePropertyChanged("CAVV");
            }
        }
        
        /// <comentarios/>
        public string CAVV_Algorithm {
            get {
                return this.cAVV_AlgorithmField;
            }
            set {
                this.cAVV_AlgorithmField = value;
                this.RaisePropertyChanged("CAVV_Algorithm");
            }
        }
        
        /// <comentarios/>
        public string Reference_No {
            get {
                return this.reference_NoField;
            }
            set {
                this.reference_NoField = value;
                this.RaisePropertyChanged("Reference_No");
            }
        }
        
        /// <comentarios/>
        public string Customer_Ref {
            get {
                return this.customer_RefField;
            }
            set {
                this.customer_RefField = value;
                this.RaisePropertyChanged("Customer_Ref");
            }
        }
        
        /// <comentarios/>
        public string Reference_3 {
            get {
                return this.reference_3Field;
            }
            set {
                this.reference_3Field = value;
                this.RaisePropertyChanged("Reference_3");
            }
        }
        
        /// <comentarios/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <comentarios/>
        public string Client_IP {
            get {
                return this.client_IPField;
            }
            set {
                this.client_IPField = value;
                this.RaisePropertyChanged("Client_IP");
            }
        }
        
        /// <comentarios/>
        public string Client_Email {
            get {
                return this.client_EmailField;
            }
            set {
                this.client_EmailField = value;
                this.RaisePropertyChanged("Client_Email");
            }
        }
        
        /// <comentarios/>
        public string User_Name {
            get {
                return this.user_NameField;
            }
            set {
                this.user_NameField = value;
                this.RaisePropertyChanged("User_Name");
            }
        }
        
        /// <comentarios/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <comentarios/>
        public bool PartialRedemption {
            get {
                return this.partialRedemptionField;
            }
            set {
                this.partialRedemptionField = value;
                this.RaisePropertyChanged("PartialRedemption");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool PartialRedemptionSpecified {
            get {
                return this.partialRedemptionFieldSpecified;
            }
            set {
                this.partialRedemptionFieldSpecified = value;
                this.RaisePropertyChanged("PartialRedemptionSpecified");
            }
        }
        
        /// <comentarios/>
        public Level3_Type Level3 {
            get {
                return this.level3Field;
            }
            set {
                this.level3Field = value;
                this.RaisePropertyChanged("Level3");
            }
        }
        
        /// <comentarios/>
        public string TransarmorToken {
            get {
                return this.transarmorTokenField;
            }
            set {
                this.transarmorTokenField = value;
                this.RaisePropertyChanged("TransarmorToken");
            }
        }
        
        /// <comentarios/>
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
                this.RaisePropertyChanged("CardType");
            }
        }
        
        /// <comentarios/>
        public string EAN {
            get {
                return this.eANField;
            }
            set {
                this.eANField = value;
                this.RaisePropertyChanged("EAN");
            }
        }
        
        /// <comentarios/>
        public bool VirtualCard {
            get {
                return this.virtualCardField;
            }
            set {
                this.virtualCardField = value;
                this.RaisePropertyChanged("VirtualCard");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool VirtualCardSpecified {
            get {
                return this.virtualCardFieldSpecified;
            }
            set {
                this.virtualCardFieldSpecified = value;
                this.RaisePropertyChanged("VirtualCardSpecified");
            }
        }
        
        /// <comentarios/>
        public string CardCost {
            get {
                return this.cardCostField;
            }
            set {
                this.cardCostField = value;
                this.RaisePropertyChanged("CardCost");
            }
        }
        
        /// <comentarios/>
        public string FraudSuspected {
            get {
                return this.fraudSuspectedField;
            }
            set {
                this.fraudSuspectedField = value;
                this.RaisePropertyChanged("FraudSuspected");
            }
        }
        
        /// <comentarios/>
        public PaypalTransactionDetails PaypalResponse {
            get {
                return this.paypalResponseField;
            }
            set {
                this.paypalResponseField = value;
                this.RaisePropertyChanged("PaypalResponse");
            }
        }
        
        /// <comentarios/>
        public SoftDescriptor_Type SoftDescriptor {
            get {
                return this.softDescriptorField;
            }
            set {
                this.softDescriptorField = value;
                this.RaisePropertyChanged("SoftDescriptor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class Level3_Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string taxAmountField;
        
        private string taxRateField;
        
        private string altTaxAmountField;
        
        private string altTaxIdField;
        
        private string dutyAmountField;
        
        private string freightAmountField;
        
        private string discountAmountField;
        
        private string shipFromZipField;
        
        private Level3_ShipToAddress_Type shipToAddressField;
        
        private Level3_LineItem_Type[] lineItemField;
        
        /// <comentarios/>
        public string TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
                this.RaisePropertyChanged("TaxAmount");
            }
        }
        
        /// <comentarios/>
        public string TaxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
                this.RaisePropertyChanged("TaxRate");
            }
        }
        
        /// <comentarios/>
        public string AltTaxAmount {
            get {
                return this.altTaxAmountField;
            }
            set {
                this.altTaxAmountField = value;
                this.RaisePropertyChanged("AltTaxAmount");
            }
        }
        
        /// <comentarios/>
        public string AltTaxId {
            get {
                return this.altTaxIdField;
            }
            set {
                this.altTaxIdField = value;
                this.RaisePropertyChanged("AltTaxId");
            }
        }
        
        /// <comentarios/>
        public string DutyAmount {
            get {
                return this.dutyAmountField;
            }
            set {
                this.dutyAmountField = value;
                this.RaisePropertyChanged("DutyAmount");
            }
        }
        
        /// <comentarios/>
        public string FreightAmount {
            get {
                return this.freightAmountField;
            }
            set {
                this.freightAmountField = value;
                this.RaisePropertyChanged("FreightAmount");
            }
        }
        
        /// <comentarios/>
        public string DiscountAmount {
            get {
                return this.discountAmountField;
            }
            set {
                this.discountAmountField = value;
                this.RaisePropertyChanged("DiscountAmount");
            }
        }
        
        /// <comentarios/>
        public string ShipFromZip {
            get {
                return this.shipFromZipField;
            }
            set {
                this.shipFromZipField = value;
                this.RaisePropertyChanged("ShipFromZip");
            }
        }
        
        /// <comentarios/>
        public Level3_ShipToAddress_Type ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
                this.RaisePropertyChanged("ShipToAddress");
            }
        }
        
        /// <comentarios/>
        public Level3_LineItem_Type[] LineItem {
            get {
                return this.lineItemField;
            }
            set {
                this.lineItemField = value;
                this.RaisePropertyChanged("LineItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class Level3_ShipToAddress_Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string address1Field;
        
        private string cityField;
        
        private string stateField;
        
        private string countryField;
        
        private string customerNumberField;
        
        private string emailField;
        
        private string phoneField;
        
        private string nameField;
        
        private string zipField;
        
        /// <comentarios/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <comentarios/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <comentarios/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <comentarios/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <comentarios/>
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
                this.RaisePropertyChanged("CustomerNumber");
            }
        }
        
        /// <comentarios/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <comentarios/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <comentarios/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <comentarios/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CheckTransactionResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class CheckTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exactIDField;
        
        private string passwordField;
        
        private string transaction_TypeField;
        
        private string dollarAmountField;
        
        private string checkTypeField;
        
        private string mICRField;
        
        private string checkNumberField;
        
        private string bankAccountNumberField;
        
        private string bankRoutingNumberField;
        
        private string transaction_TagField;
        
        private string authorization_NumField;
        
        private string customerNameField;
        
        private string verificationStr1Field;
        
        private string ecommerce_FlagField;
        
        private string reference_NoField;
        
        private string customer_RefField;
        
        private string languageField;
        
        private string client_IPField;
        
        private string client_EmailField;
        
        private string user_NameField;
        
        private string customerIDTypeField;
        
        private string customerIDField;
        
        private string releaseTypeField;
        
        private string giftCardAmountField;
        
        private string dateOfBirthField;
        
        private bool vIPField;
        
        private bool vIPFieldSpecified;
        
        private string registrationNoField;
        
        private string registrationDateField;
        
        private string clerkIDField;
        
        private string deviceIDField;
        
        /// <comentarios/>
        public string ExactID {
            get {
                return this.exactIDField;
            }
            set {
                this.exactIDField = value;
                this.RaisePropertyChanged("ExactID");
            }
        }
        
        /// <comentarios/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <comentarios/>
        public string Transaction_Type {
            get {
                return this.transaction_TypeField;
            }
            set {
                this.transaction_TypeField = value;
                this.RaisePropertyChanged("Transaction_Type");
            }
        }
        
        /// <comentarios/>
        public string DollarAmount {
            get {
                return this.dollarAmountField;
            }
            set {
                this.dollarAmountField = value;
                this.RaisePropertyChanged("DollarAmount");
            }
        }
        
        /// <comentarios/>
        public string CheckType {
            get {
                return this.checkTypeField;
            }
            set {
                this.checkTypeField = value;
                this.RaisePropertyChanged("CheckType");
            }
        }
        
        /// <comentarios/>
        public string MICR {
            get {
                return this.mICRField;
            }
            set {
                this.mICRField = value;
                this.RaisePropertyChanged("MICR");
            }
        }
        
        /// <comentarios/>
        public string CheckNumber {
            get {
                return this.checkNumberField;
            }
            set {
                this.checkNumberField = value;
                this.RaisePropertyChanged("CheckNumber");
            }
        }
        
        /// <comentarios/>
        public string BankAccountNumber {
            get {
                return this.bankAccountNumberField;
            }
            set {
                this.bankAccountNumberField = value;
                this.RaisePropertyChanged("BankAccountNumber");
            }
        }
        
        /// <comentarios/>
        public string BankRoutingNumber {
            get {
                return this.bankRoutingNumberField;
            }
            set {
                this.bankRoutingNumberField = value;
                this.RaisePropertyChanged("BankRoutingNumber");
            }
        }
        
        /// <comentarios/>
        public string Transaction_Tag {
            get {
                return this.transaction_TagField;
            }
            set {
                this.transaction_TagField = value;
                this.RaisePropertyChanged("Transaction_Tag");
            }
        }
        
        /// <comentarios/>
        public string Authorization_Num {
            get {
                return this.authorization_NumField;
            }
            set {
                this.authorization_NumField = value;
                this.RaisePropertyChanged("Authorization_Num");
            }
        }
        
        /// <comentarios/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <comentarios/>
        public string VerificationStr1 {
            get {
                return this.verificationStr1Field;
            }
            set {
                this.verificationStr1Field = value;
                this.RaisePropertyChanged("VerificationStr1");
            }
        }
        
        /// <comentarios/>
        public string Ecommerce_Flag {
            get {
                return this.ecommerce_FlagField;
            }
            set {
                this.ecommerce_FlagField = value;
                this.RaisePropertyChanged("Ecommerce_Flag");
            }
        }
        
        /// <comentarios/>
        public string Reference_No {
            get {
                return this.reference_NoField;
            }
            set {
                this.reference_NoField = value;
                this.RaisePropertyChanged("Reference_No");
            }
        }
        
        /// <comentarios/>
        public string Customer_Ref {
            get {
                return this.customer_RefField;
            }
            set {
                this.customer_RefField = value;
                this.RaisePropertyChanged("Customer_Ref");
            }
        }
        
        /// <comentarios/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <comentarios/>
        public string Client_IP {
            get {
                return this.client_IPField;
            }
            set {
                this.client_IPField = value;
                this.RaisePropertyChanged("Client_IP");
            }
        }
        
        /// <comentarios/>
        public string Client_Email {
            get {
                return this.client_EmailField;
            }
            set {
                this.client_EmailField = value;
                this.RaisePropertyChanged("Client_Email");
            }
        }
        
        /// <comentarios/>
        public string User_Name {
            get {
                return this.user_NameField;
            }
            set {
                this.user_NameField = value;
                this.RaisePropertyChanged("User_Name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string CustomerIDType {
            get {
                return this.customerIDTypeField;
            }
            set {
                this.customerIDTypeField = value;
                this.RaisePropertyChanged("CustomerIDType");
            }
        }
        
        /// <comentarios/>
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <comentarios/>
        public string ReleaseType {
            get {
                return this.releaseTypeField;
            }
            set {
                this.releaseTypeField = value;
                this.RaisePropertyChanged("ReleaseType");
            }
        }
        
        /// <comentarios/>
        public string GiftCardAmount {
            get {
                return this.giftCardAmountField;
            }
            set {
                this.giftCardAmountField = value;
                this.RaisePropertyChanged("GiftCardAmount");
            }
        }
        
        /// <comentarios/>
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("DateOfBirth");
            }
        }
        
        /// <comentarios/>
        public bool VIP {
            get {
                return this.vIPField;
            }
            set {
                this.vIPField = value;
                this.RaisePropertyChanged("VIP");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool VIPSpecified {
            get {
                return this.vIPFieldSpecified;
            }
            set {
                this.vIPFieldSpecified = value;
                this.RaisePropertyChanged("VIPSpecified");
            }
        }
        
        /// <comentarios/>
        public string RegistrationNo {
            get {
                return this.registrationNoField;
            }
            set {
                this.registrationNoField = value;
                this.RaisePropertyChanged("RegistrationNo");
            }
        }
        
        /// <comentarios/>
        public string RegistrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
                this.RaisePropertyChanged("RegistrationDate");
            }
        }
        
        /// <comentarios/>
        public string ClerkID {
            get {
                return this.clerkIDField;
            }
            set {
                this.clerkIDField = value;
                this.RaisePropertyChanged("ClerkID");
            }
        }
        
        /// <comentarios/>
        public string DeviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
                this.RaisePropertyChanged("DeviceID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class CheckTransactionResult : CheckTransaction {
        
        private bool transaction_ErrorField;
        
        private bool transaction_ApprovedField;
        
        private string eXact_Resp_CodeField;
        
        private string eXact_MessageField;
        
        private string bank_Resp_CodeField;
        
        private string bank_MessageField;
        
        private string bank_Resp_Code_2Field;
        
        private string sequenceNoField;
        
        private string merchantNameField;
        
        private string merchantAddressField;
        
        private string merchantCityField;
        
        private string merchantProvinceField;
        
        private string merchantCountryField;
        
        private string merchantPostalField;
        
        private string merchantURLField;
        
        private string cTRField;
        
        /// <comentarios/>
        public bool Transaction_Error {
            get {
                return this.transaction_ErrorField;
            }
            set {
                this.transaction_ErrorField = value;
                this.RaisePropertyChanged("Transaction_Error");
            }
        }
        
        /// <comentarios/>
        public bool Transaction_Approved {
            get {
                return this.transaction_ApprovedField;
            }
            set {
                this.transaction_ApprovedField = value;
                this.RaisePropertyChanged("Transaction_Approved");
            }
        }
        
        /// <comentarios/>
        public string EXact_Resp_Code {
            get {
                return this.eXact_Resp_CodeField;
            }
            set {
                this.eXact_Resp_CodeField = value;
                this.RaisePropertyChanged("EXact_Resp_Code");
            }
        }
        
        /// <comentarios/>
        public string EXact_Message {
            get {
                return this.eXact_MessageField;
            }
            set {
                this.eXact_MessageField = value;
                this.RaisePropertyChanged("EXact_Message");
            }
        }
        
        /// <comentarios/>
        public string Bank_Resp_Code {
            get {
                return this.bank_Resp_CodeField;
            }
            set {
                this.bank_Resp_CodeField = value;
                this.RaisePropertyChanged("Bank_Resp_Code");
            }
        }
        
        /// <comentarios/>
        public string Bank_Message {
            get {
                return this.bank_MessageField;
            }
            set {
                this.bank_MessageField = value;
                this.RaisePropertyChanged("Bank_Message");
            }
        }
        
        /// <comentarios/>
        public string Bank_Resp_Code_2 {
            get {
                return this.bank_Resp_Code_2Field;
            }
            set {
                this.bank_Resp_Code_2Field = value;
                this.RaisePropertyChanged("Bank_Resp_Code_2");
            }
        }
        
        /// <comentarios/>
        public string SequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("SequenceNo");
            }
        }
        
        /// <comentarios/>
        public string MerchantName {
            get {
                return this.merchantNameField;
            }
            set {
                this.merchantNameField = value;
                this.RaisePropertyChanged("MerchantName");
            }
        }
        
        /// <comentarios/>
        public string MerchantAddress {
            get {
                return this.merchantAddressField;
            }
            set {
                this.merchantAddressField = value;
                this.RaisePropertyChanged("MerchantAddress");
            }
        }
        
        /// <comentarios/>
        public string MerchantCity {
            get {
                return this.merchantCityField;
            }
            set {
                this.merchantCityField = value;
                this.RaisePropertyChanged("MerchantCity");
            }
        }
        
        /// <comentarios/>
        public string MerchantProvince {
            get {
                return this.merchantProvinceField;
            }
            set {
                this.merchantProvinceField = value;
                this.RaisePropertyChanged("MerchantProvince");
            }
        }
        
        /// <comentarios/>
        public string MerchantCountry {
            get {
                return this.merchantCountryField;
            }
            set {
                this.merchantCountryField = value;
                this.RaisePropertyChanged("MerchantCountry");
            }
        }
        
        /// <comentarios/>
        public string MerchantPostal {
            get {
                return this.merchantPostalField;
            }
            set {
                this.merchantPostalField = value;
                this.RaisePropertyChanged("MerchantPostal");
            }
        }
        
        /// <comentarios/>
        public string MerchantURL {
            get {
                return this.merchantURLField;
            }
            set {
                this.merchantURLField = value;
                this.RaisePropertyChanged("MerchantURL");
            }
        }
        
        /// <comentarios/>
        public string CTR {
            get {
                return this.cTRField;
            }
            set {
                this.cTRField = value;
                this.RaisePropertyChanged("CTR");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class SoftDescriptor_Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dBANameField;
        
        private string streetField;
        
        private string cityField;
        
        private string regionField;
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        private string mIDField;
        
        private string mCCField;
        
        private string merchantContactInfoField;
        
        /// <comentarios/>
        public string DBAName {
            get {
                return this.dBANameField;
            }
            set {
                this.dBANameField = value;
                this.RaisePropertyChanged("DBAName");
            }
        }
        
        /// <comentarios/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <comentarios/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <comentarios/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <comentarios/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <comentarios/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <comentarios/>
        public string MID {
            get {
                return this.mIDField;
            }
            set {
                this.mIDField = value;
                this.RaisePropertyChanged("MID");
            }
        }
        
        /// <comentarios/>
        public string MCC {
            get {
                return this.mCCField;
            }
            set {
                this.mCCField = value;
                this.RaisePropertyChanged("MCC");
            }
        }
        
        /// <comentarios/>
        public string MerchantContactInfo {
            get {
                return this.merchantContactInfoField;
            }
            set {
                this.merchantContactInfoField = value;
                this.RaisePropertyChanged("MerchantContactInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class PaypalTransactionDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string payerIDField;
        
        private string grossAmountCurrencyIDField;
        
        private bool successField;
        
        private string authorizationField;
        
        private string messageField;
        
        private string correlationIDField;
        
        private string timestampField;
        
        /// <comentarios/>
        public string PayerID {
            get {
                return this.payerIDField;
            }
            set {
                this.payerIDField = value;
                this.RaisePropertyChanged("PayerID");
            }
        }
        
        /// <comentarios/>
        public string GrossAmountCurrencyID {
            get {
                return this.grossAmountCurrencyIDField;
            }
            set {
                this.grossAmountCurrencyIDField = value;
                this.RaisePropertyChanged("GrossAmountCurrencyID");
            }
        }
        
        /// <comentarios/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <comentarios/>
        public string Authorization {
            get {
                return this.authorizationField;
            }
            set {
                this.authorizationField = value;
                this.RaisePropertyChanged("Authorization");
            }
        }
        
        /// <comentarios/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <comentarios/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
                this.RaisePropertyChanged("CorrelationID");
            }
        }
        
        /// <comentarios/>
        public string Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class Level3_LineItem_Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string commodityCodeField;
        
        private string descriptionField;
        
        private string discountAmountField;
        
        private bool discountIndicatorField;
        
        private bool discountIndicatorFieldSpecified;
        
        private bool grossNetIndicatorField;
        
        private bool grossNetIndicatorFieldSpecified;
        
        private string lineItemTotalField;
        
        private string productCodeField;
        
        private string quantityField;
        
        private string taxAmountField;
        
        private string taxRateField;
        
        private string taxTypeField;
        
        private string unitCostField;
        
        private string unitOfMeasureField;
        
        /// <comentarios/>
        public string CommodityCode {
            get {
                return this.commodityCodeField;
            }
            set {
                this.commodityCodeField = value;
                this.RaisePropertyChanged("CommodityCode");
            }
        }
        
        /// <comentarios/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <comentarios/>
        public string DiscountAmount {
            get {
                return this.discountAmountField;
            }
            set {
                this.discountAmountField = value;
                this.RaisePropertyChanged("DiscountAmount");
            }
        }
        
        /// <comentarios/>
        public bool DiscountIndicator {
            get {
                return this.discountIndicatorField;
            }
            set {
                this.discountIndicatorField = value;
                this.RaisePropertyChanged("DiscountIndicator");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool DiscountIndicatorSpecified {
            get {
                return this.discountIndicatorFieldSpecified;
            }
            set {
                this.discountIndicatorFieldSpecified = value;
                this.RaisePropertyChanged("DiscountIndicatorSpecified");
            }
        }
        
        /// <comentarios/>
        public bool GrossNetIndicator {
            get {
                return this.grossNetIndicatorField;
            }
            set {
                this.grossNetIndicatorField = value;
                this.RaisePropertyChanged("GrossNetIndicator");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool GrossNetIndicatorSpecified {
            get {
                return this.grossNetIndicatorFieldSpecified;
            }
            set {
                this.grossNetIndicatorFieldSpecified = value;
                this.RaisePropertyChanged("GrossNetIndicatorSpecified");
            }
        }
        
        /// <comentarios/>
        public string LineItemTotal {
            get {
                return this.lineItemTotalField;
            }
            set {
                this.lineItemTotalField = value;
                this.RaisePropertyChanged("LineItemTotal");
            }
        }
        
        /// <comentarios/>
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <comentarios/>
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <comentarios/>
        public string TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
                this.RaisePropertyChanged("TaxAmount");
            }
        }
        
        /// <comentarios/>
        public string TaxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
                this.RaisePropertyChanged("TaxRate");
            }
        }
        
        /// <comentarios/>
        public string TaxType {
            get {
                return this.taxTypeField;
            }
            set {
                this.taxTypeField = value;
                this.RaisePropertyChanged("TaxType");
            }
        }
        
        /// <comentarios/>
        public string UnitCost {
            get {
                return this.unitCostField;
            }
            set {
                this.unitCostField = value;
                this.RaisePropertyChanged("UnitCost");
            }
        }
        
        /// <comentarios/>
        public string UnitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
                this.RaisePropertyChanged("UnitOfMeasure");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")]
    public partial class TransactionResult : Transaction {
        
        private bool transaction_ErrorField;
        
        private bool transaction_ApprovedField;
        
        private string eXact_Resp_CodeField;
        
        private string eXact_MessageField;
        
        private string bank_Resp_CodeField;
        
        private string bank_MessageField;
        
        private string bank_Resp_Code_2Field;
        
        private string sequenceNoField;
        
        private string aVSField;
        
        private string cVV2Field;
        
        private string retrieval_Ref_NoField;
        
        private string cAVV_ResponseField;
        
        private string amountRequestedField;
        
        private string merchantNameField;
        
        private string merchantAddressField;
        
        private string merchantCityField;
        
        private string merchantProvinceField;
        
        private string merchantCountryField;
        
        private string merchantPostalField;
        
        private string merchantURLField;
        
        private string currentBalanceField;
        
        private string previousBalanceField;
        
        private string cTRField;
        
        /// <comentarios/>
        public bool Transaction_Error {
            get {
                return this.transaction_ErrorField;
            }
            set {
                this.transaction_ErrorField = value;
                this.RaisePropertyChanged("Transaction_Error");
            }
        }
        
        /// <comentarios/>
        public bool Transaction_Approved {
            get {
                return this.transaction_ApprovedField;
            }
            set {
                this.transaction_ApprovedField = value;
                this.RaisePropertyChanged("Transaction_Approved");
            }
        }
        
        /// <comentarios/>
        public string EXact_Resp_Code {
            get {
                return this.eXact_Resp_CodeField;
            }
            set {
                this.eXact_Resp_CodeField = value;
                this.RaisePropertyChanged("EXact_Resp_Code");
            }
        }
        
        /// <comentarios/>
        public string EXact_Message {
            get {
                return this.eXact_MessageField;
            }
            set {
                this.eXact_MessageField = value;
                this.RaisePropertyChanged("EXact_Message");
            }
        }
        
        /// <comentarios/>
        public string Bank_Resp_Code {
            get {
                return this.bank_Resp_CodeField;
            }
            set {
                this.bank_Resp_CodeField = value;
                this.RaisePropertyChanged("Bank_Resp_Code");
            }
        }
        
        /// <comentarios/>
        public string Bank_Message {
            get {
                return this.bank_MessageField;
            }
            set {
                this.bank_MessageField = value;
                this.RaisePropertyChanged("Bank_Message");
            }
        }
        
        /// <comentarios/>
        public string Bank_Resp_Code_2 {
            get {
                return this.bank_Resp_Code_2Field;
            }
            set {
                this.bank_Resp_Code_2Field = value;
                this.RaisePropertyChanged("Bank_Resp_Code_2");
            }
        }
        
        /// <comentarios/>
        public string SequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("SequenceNo");
            }
        }
        
        /// <comentarios/>
        public string AVS {
            get {
                return this.aVSField;
            }
            set {
                this.aVSField = value;
                this.RaisePropertyChanged("AVS");
            }
        }
        
        /// <comentarios/>
        public string CVV2 {
            get {
                return this.cVV2Field;
            }
            set {
                this.cVV2Field = value;
                this.RaisePropertyChanged("CVV2");
            }
        }
        
        /// <comentarios/>
        public string Retrieval_Ref_No {
            get {
                return this.retrieval_Ref_NoField;
            }
            set {
                this.retrieval_Ref_NoField = value;
                this.RaisePropertyChanged("Retrieval_Ref_No");
            }
        }
        
        /// <comentarios/>
        public string CAVV_Response {
            get {
                return this.cAVV_ResponseField;
            }
            set {
                this.cAVV_ResponseField = value;
                this.RaisePropertyChanged("CAVV_Response");
            }
        }
        
        /// <comentarios/>
        public string AmountRequested {
            get {
                return this.amountRequestedField;
            }
            set {
                this.amountRequestedField = value;
                this.RaisePropertyChanged("AmountRequested");
            }
        }
        
        /// <comentarios/>
        public string MerchantName {
            get {
                return this.merchantNameField;
            }
            set {
                this.merchantNameField = value;
                this.RaisePropertyChanged("MerchantName");
            }
        }
        
        /// <comentarios/>
        public string MerchantAddress {
            get {
                return this.merchantAddressField;
            }
            set {
                this.merchantAddressField = value;
                this.RaisePropertyChanged("MerchantAddress");
            }
        }
        
        /// <comentarios/>
        public string MerchantCity {
            get {
                return this.merchantCityField;
            }
            set {
                this.merchantCityField = value;
                this.RaisePropertyChanged("MerchantCity");
            }
        }
        
        /// <comentarios/>
        public string MerchantProvince {
            get {
                return this.merchantProvinceField;
            }
            set {
                this.merchantProvinceField = value;
                this.RaisePropertyChanged("MerchantProvince");
            }
        }
        
        /// <comentarios/>
        public string MerchantCountry {
            get {
                return this.merchantCountryField;
            }
            set {
                this.merchantCountryField = value;
                this.RaisePropertyChanged("MerchantCountry");
            }
        }
        
        /// <comentarios/>
        public string MerchantPostal {
            get {
                return this.merchantPostalField;
            }
            set {
                this.merchantPostalField = value;
                this.RaisePropertyChanged("MerchantPostal");
            }
        }
        
        /// <comentarios/>
        public string MerchantURL {
            get {
                return this.merchantURLField;
            }
            set {
                this.merchantURLField = value;
                this.RaisePropertyChanged("MerchantURL");
            }
        }
        
        /// <comentarios/>
        public string CurrentBalance {
            get {
                return this.currentBalanceField;
            }
            set {
                this.currentBalanceField = value;
                this.RaisePropertyChanged("CurrentBalance");
            }
        }
        
        /// <comentarios/>
        public string PreviousBalance {
            get {
                return this.previousBalanceField;
            }
            set {
                this.previousBalanceField = value;
                this.RaisePropertyChanged("PreviousBalance");
            }
        }
        
        /// <comentarios/>
        public string CTR {
            get {
                return this.cTRField;
            }
            set {
                this.cTRField = value;
                this.RaisePropertyChanged("CTR");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAndCommit", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request", IsWrapped=true)]
    public partial class SendAndCommitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TimelyDepotMVC.GGE4ServiceReference.Transaction SendAndCommitSource;
        
        public SendAndCommitRequest() {
        }
        
        public SendAndCommitRequest(TimelyDepotMVC.GGE4ServiceReference.Transaction SendAndCommitSource) {
            this.SendAndCommitSource = SendAndCommitSource;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAndCommitResponse", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Response", IsWrapped=true)]
    public partial class SendAndCommitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TimelyDepotMVC.GGE4ServiceReference.TransactionResult SendAndCommitResult;
        
        public SendAndCommitResponse() {
        }
        
        public SendAndCommitResponse(TimelyDepotMVC.GGE4ServiceReference.TransactionResult SendAndCommitResult) {
            this.SendAndCommitResult = SendAndCommitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAndCommitCheck", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request", IsWrapped=true)]
    public partial class SendAndCommitCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TimelyDepotMVC.GGE4ServiceReference.CheckTransaction SendAndCommitCheckSource;
        
        public SendAndCommitCheckRequest() {
        }
        
        public SendAndCommitCheckRequest(TimelyDepotMVC.GGE4ServiceReference.CheckTransaction SendAndCommitCheckSource) {
            this.SendAndCommitCheckSource = SendAndCommitCheckSource;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAndCommitCheckResponse", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Response", IsWrapped=true)]
    public partial class SendAndCommitCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TimelyDepotMVC.GGE4ServiceReference.CheckTransactionResult SendAndCommitCheckResult;
        
        public SendAndCommitCheckResponse() {
        }
        
        public SendAndCommitCheckResponse(TimelyDepotMVC.GGE4ServiceReference.CheckTransactionResult SendAndCommitCheckResult) {
            this.SendAndCommitCheckResult = SendAndCommitCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransactionInfo", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request", IsWrapped=true)]
    public partial class TransactionInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TimelyDepotMVC.GGE4ServiceReference.Transaction TransactionInfoSource;
        
        public TransactionInfoRequest() {
        }
        
        public TransactionInfoRequest(TimelyDepotMVC.GGE4ServiceReference.Transaction TransactionInfoSource) {
            this.TransactionInfoSource = TransactionInfoSource;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransactionInfoResponse", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Response", IsWrapped=true)]
    public partial class TransactionInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TimelyDepotMVC.GGE4ServiceReference.TransactionResult TransactionInfoResult;
        
        public TransactionInfoResponse() {
        }
        
        public TransactionInfoResponse(TimelyDepotMVC.GGE4ServiceReference.TransactionResult TransactionInfoResult) {
            this.TransactionInfoResult = TransactionInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTransactionInfo", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request", IsWrapped=true)]
    public partial class CheckTransactionInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TimelyDepotMVC.GGE4ServiceReference.CheckTransaction CheckTransactionInfoSource;
        
        public CheckTransactionInfoRequest() {
        }
        
        public CheckTransactionInfoRequest(TimelyDepotMVC.GGE4ServiceReference.CheckTransaction CheckTransactionInfoSource) {
            this.CheckTransactionInfoSource = CheckTransactionInfoSource;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTransactionInfoResponse", WrapperNamespace="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Response", IsWrapped=true)]
    public partial class CheckTransactionInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public TimelyDepotMVC.GGE4ServiceReference.CheckTransactionResult CheckTransactionInfoResult;
        
        public CheckTransactionInfoResponse() {
        }
        
        public CheckTransactionInfoResponse(TimelyDepotMVC.GGE4ServiceReference.CheckTransactionResult CheckTransactionInfoResult) {
            this.CheckTransactionInfoResult = CheckTransactionInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : TimelyDepotMVC.GGE4ServiceReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<TimelyDepotMVC.GGE4ServiceReference.ServiceSoap>, TimelyDepotMVC.GGE4ServiceReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimelyDepotMVC.GGE4ServiceReference.SendAndCommitResponse TimelyDepotMVC.GGE4ServiceReference.ServiceSoap.SendAndCommit(TimelyDepotMVC.GGE4ServiceReference.SendAndCommitRequest request) {
            return base.Channel.SendAndCommit(request);
        }
        
        public TimelyDepotMVC.GGE4ServiceReference.TransactionResult SendAndCommit(TimelyDepotMVC.GGE4ServiceReference.Transaction SendAndCommitSource) {
            TimelyDepotMVC.GGE4ServiceReference.SendAndCommitRequest inValue = new TimelyDepotMVC.GGE4ServiceReference.SendAndCommitRequest();
            inValue.SendAndCommitSource = SendAndCommitSource;
            TimelyDepotMVC.GGE4ServiceReference.SendAndCommitResponse retVal = ((TimelyDepotMVC.GGE4ServiceReference.ServiceSoap)(this)).SendAndCommit(inValue);
            return retVal.SendAndCommitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimelyDepotMVC.GGE4ServiceReference.SendAndCommitResponse> TimelyDepotMVC.GGE4ServiceReference.ServiceSoap.SendAndCommitAsync(TimelyDepotMVC.GGE4ServiceReference.SendAndCommitRequest request) {
            return base.Channel.SendAndCommitAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimelyDepotMVC.GGE4ServiceReference.SendAndCommitResponse> SendAndCommitAsync(TimelyDepotMVC.GGE4ServiceReference.Transaction SendAndCommitSource) {
            TimelyDepotMVC.GGE4ServiceReference.SendAndCommitRequest inValue = new TimelyDepotMVC.GGE4ServiceReference.SendAndCommitRequest();
            inValue.SendAndCommitSource = SendAndCommitSource;
            return ((TimelyDepotMVC.GGE4ServiceReference.ServiceSoap)(this)).SendAndCommitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckResponse TimelyDepotMVC.GGE4ServiceReference.ServiceSoap.SendAndCommitCheck(TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckRequest request) {
            return base.Channel.SendAndCommitCheck(request);
        }
        
        public TimelyDepotMVC.GGE4ServiceReference.CheckTransactionResult SendAndCommitCheck(TimelyDepotMVC.GGE4ServiceReference.CheckTransaction SendAndCommitCheckSource) {
            TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckRequest inValue = new TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckRequest();
            inValue.SendAndCommitCheckSource = SendAndCommitCheckSource;
            TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckResponse retVal = ((TimelyDepotMVC.GGE4ServiceReference.ServiceSoap)(this)).SendAndCommitCheck(inValue);
            return retVal.SendAndCommitCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckResponse> TimelyDepotMVC.GGE4ServiceReference.ServiceSoap.SendAndCommitCheckAsync(TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckRequest request) {
            return base.Channel.SendAndCommitCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckResponse> SendAndCommitCheckAsync(TimelyDepotMVC.GGE4ServiceReference.CheckTransaction SendAndCommitCheckSource) {
            TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckRequest inValue = new TimelyDepotMVC.GGE4ServiceReference.SendAndCommitCheckRequest();
            inValue.SendAndCommitCheckSource = SendAndCommitCheckSource;
            return ((TimelyDepotMVC.GGE4ServiceReference.ServiceSoap)(this)).SendAndCommitCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimelyDepotMVC.GGE4ServiceReference.TransactionInfoResponse TimelyDepotMVC.GGE4ServiceReference.ServiceSoap.TransactionInfo(TimelyDepotMVC.GGE4ServiceReference.TransactionInfoRequest request) {
            return base.Channel.TransactionInfo(request);
        }
        
        public TimelyDepotMVC.GGE4ServiceReference.TransactionResult TransactionInfo(TimelyDepotMVC.GGE4ServiceReference.Transaction TransactionInfoSource) {
            TimelyDepotMVC.GGE4ServiceReference.TransactionInfoRequest inValue = new TimelyDepotMVC.GGE4ServiceReference.TransactionInfoRequest();
            inValue.TransactionInfoSource = TransactionInfoSource;
            TimelyDepotMVC.GGE4ServiceReference.TransactionInfoResponse retVal = ((TimelyDepotMVC.GGE4ServiceReference.ServiceSoap)(this)).TransactionInfo(inValue);
            return retVal.TransactionInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimelyDepotMVC.GGE4ServiceReference.TransactionInfoResponse> TimelyDepotMVC.GGE4ServiceReference.ServiceSoap.TransactionInfoAsync(TimelyDepotMVC.GGE4ServiceReference.TransactionInfoRequest request) {
            return base.Channel.TransactionInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimelyDepotMVC.GGE4ServiceReference.TransactionInfoResponse> TransactionInfoAsync(TimelyDepotMVC.GGE4ServiceReference.Transaction TransactionInfoSource) {
            TimelyDepotMVC.GGE4ServiceReference.TransactionInfoRequest inValue = new TimelyDepotMVC.GGE4ServiceReference.TransactionInfoRequest();
            inValue.TransactionInfoSource = TransactionInfoSource;
            return ((TimelyDepotMVC.GGE4ServiceReference.ServiceSoap)(this)).TransactionInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoResponse TimelyDepotMVC.GGE4ServiceReference.ServiceSoap.CheckTransactionInfo(TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoRequest request) {
            return base.Channel.CheckTransactionInfo(request);
        }
        
        public TimelyDepotMVC.GGE4ServiceReference.CheckTransactionResult CheckTransactionInfo(TimelyDepotMVC.GGE4ServiceReference.CheckTransaction CheckTransactionInfoSource) {
            TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoRequest inValue = new TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoRequest();
            inValue.CheckTransactionInfoSource = CheckTransactionInfoSource;
            TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoResponse retVal = ((TimelyDepotMVC.GGE4ServiceReference.ServiceSoap)(this)).CheckTransactionInfo(inValue);
            return retVal.CheckTransactionInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoResponse> TimelyDepotMVC.GGE4ServiceReference.ServiceSoap.CheckTransactionInfoAsync(TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoRequest request) {
            return base.Channel.CheckTransactionInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoResponse> CheckTransactionInfoAsync(TimelyDepotMVC.GGE4ServiceReference.CheckTransaction CheckTransactionInfoSource) {
            TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoRequest inValue = new TimelyDepotMVC.GGE4ServiceReference.CheckTransactionInfoRequest();
            inValue.CheckTransactionInfoSource = CheckTransactionInfoSource;
            return ((TimelyDepotMVC.GGE4ServiceReference.ServiceSoap)(this)).CheckTransactionInfoAsync(inValue);
        }
    }
}
