// <auto-generated />
namespace TimelyDepotMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class PasswrodAndGatewayObligated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PasswrodAndGatewayObligated));
        
        string IMigrationMetadata.Id
        {
            get { return "201410201317187_PasswrodAndGatewayObligated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
