// <auto-generated />
namespace TimelyDepotMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class InvoicePaymentToPaymentTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InvoicePaymentToPaymentTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201507151135322_InvoicePaymentToPaymentTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
